//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DIACHIGH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIACHIGH()
        {
            this.DATHANGs = new HashSet<DATHANG>();
        }

        public int MADIACHI { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        [StringLength(50, ErrorMessage = "Không được nhập quá 50 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập tên")]
        public string HOTEN { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập số điện thoại")]
        public int SDT { get; set; }
        [StringLength(50, ErrorMessage = "Không được nhập quá 50 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập địa chỉ")]
        public string SONHA { get; set; }
        [StringLength(20, ErrorMessage = "Không được nhập quá 20 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập phường")]
        public string PHUONG { get; set; }
        [StringLength(20, ErrorMessage = "Không được nhập quá 20 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập Quận")]
        public string QUAN { get; set; }
        public string GHICHU { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATHANG> DATHANGs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
