//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanThucAnNhanh.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.DIACHIGHs = new HashSet<DIACHIGH>();
        }

        public int MAKHACHHANG { get; set; }
        [StringLength(50, ErrorMessage = "Không được nhập quá 50 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập tên")]
        public string TENKHACHHANG { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập ngày sinh")]
        public DateTime NGAYSINH { get; set; }
        public string DIACHI { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập Số điện thoại")]
        public int SDT { get; set; }
        [StringLength(50, ErrorMessage = "Không được nhập quá 50 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập Email")]
        public string EMAIL { get; set; }
        [StringLength(30, ErrorMessage = "Không được nhập quá 30 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập Password")]
        public string PASSWORD { get; set; }
        public string LOAI { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIACHIGH> DIACHIGHs { get; set; }
        [NotMapped]
        [StringLength(30, ErrorMessage = "Không được nhập quá 30 ký tự")]
        [Required(ErrorMessage = "Bạn chưa nhập Comfirm Password")]
        public string Comfirm { get; set; }
    }
}
